### ISSUE TITLE
sync beforeCommit() instead of afterCommit()?

### ISSUE THREAD

**Issue by ydewit** [ethlo/spring-tx-cache-decorator#5]
We are seeing stale cache entries for a brief moment of time and it seems to be due to the synchronization happening after the commit.

Would it make more sense to synchronize beforeCommit()?

**Comment by ethlo** [comment]
Hi, and thanks for reporting your issue. I'm not sure how you are encountering this issue. If the transaction is committed, then the callback for the cache is called. This should make your cache updated when your method return, given that your cache update is not asynchronous. Syncing on beforeCommit() would run the risk of updating the cache and the transaction actually not being committed.

**Comment by ethlo** [comment]
Closed due to lack of feedback.

**Comment by ydewit** [comment]
@ethlo Sorry for the delayed response here. It turned out this was an issue on our side so closing makes sense.

**Comment by ethlo** [comment]
Great! Thanks for confirming 👌
