### ISSUE TITLE
Nulls being cached only when call in a transaction

### ISSUE THREAD

**Issue by ydewit** [ethlo/spring-tx-cache-decorator#8]
This seems to be a follow up to issue #6. Nulls are now cached, but only when the call is in a transaction.

Our expectation is that the underlying caching semantics is preserved with or without an ongoing transaction.

**Comment by ethlo** [comment]
Interesting find! I have never encountered that issue (as we've always used it in a transactional context), but I'll see if I can create a test for it and see what is going on :)

**Comment by ydewit** [comment]
Hi @ethlo, curious whether you were able to reproduce the problem?
